KinsonDigital/VersionMiner

README.md

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Fix issue in README file

---

.github/FUNDING.yml
VersionMiner.sln

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Setup project contributions

---

action.yml

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Change action icon for marketplace

---

Testing/VersionMinerTests/GitHubActionTests.cs
VersionMiner/GitHubAction.cs

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Add URL link to create issue to console output

---

.github/workflows/build-status-check.yml
.github/workflows/unit-tests-status-check.yml
.vscode/settings.json

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Update the build and unit testing status check workflows

---

.github/ISSUE_TEMPLATE/bug-issue-template.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request-issue-template.yml
.github/ISSUE_TEMPLATE/project-item-issue-template.yml
.github/ISSUE_TEMPLATE/release-todo-issue-template.yml
.github/ISSUE_TEMPLATE/research-issue-template.yml
.github/PULL_REQUEST_TEMPLATE/feature-pr-template.md
.github/PULL_REQUEST_TEMPLATE/preview-feature-pr-template.md
.github/PULL_REQUEST_TEMPLATE/preview-release-pr-template.md
.github/PULL_REQUEST_TEMPLATE/production-release-pr-template.md
Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.1.md

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

Update issue and PR templates

---

.github/workflows/build-status-check.yml
.github/workflows/unit-tests-status-check.yml
.run/InvalidBranch.run.xml
README.md
Testing/VersionMinerTests/GitHubActionTests.cs
Testing/VersionMinerTests/Models/RepoModelTests.cs
VersionMiner.sln
VersionMiner/ExtensionMethods.cs
VersionMiner/GitHubAction.cs
VersionMiner/Services/GitHubConsoleService.cs

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Fix branch invalid and logging issue

---

.github/workflows/unit-test-pr-status-check.yml
VersionMiner/Program.cs
VersionMiner/VersionMiner.csproj

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Move internal visible setup

---

Testing/VersionMinerIntegrationTests/VersionMinerIntegrationTests.csproj
Testing/VersionMinerTests/VersionMinerTests.csproj
VersionMiner/VersionMiner.csproj

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Update dotnet version to latest 

---

.github/workflows/build-pr-status-check.yml
.github/workflows/feature-pr-status-check.yml
.github/workflows/hotfix-pr-status-check.yml
.github/workflows/prev-feature-pr-status-check.yml
.github/workflows/prev-release-pr-status-check.yml
.github/workflows/prev-release.yml
.github/workflows/prod-release-pr-status-check.yml
.github/workflows/prod-release.yml
VersionMiner.sln

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Update workflows to use env files

---

Dockerfile
Testing/VersionMinerIntegrationTests/IntegrationTests.cs
Testing/VersionMinerTests/Services/ActionOutputServiceTests.cs
Testing/VersionMinerTests/VersionMinerTests.csproj
VersionMiner/Program.cs
VersionMiner/Services/ActionOutputService.cs
VersionMiner/Services/EnvVarService.cs
VersionMiner/Services/IEnvVarService.cs
VersionMiner/VersionMiner.csproj

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Update the actions output

---

.github/dependabot.yml

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Setup dependabot

---

codecov.yml

``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …

🚧Update codecov YML file

---

.github/workflows/build-status-check.yml
.github/workflows/unit-testing-status-check.yml
VersionMiner/VersionMiner.csproj

<h1 style="font-weight:bold" align="center">Feature Pull Request</h1>
``` xml
Syntax: feature/<issue-num>-<description>
Example: feature/123-my-feature
```
</details>
💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/BranchingFullGitFlow.md).
- One issue per pull request.
- The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's …

🚧Change branching model and workflow 

---

.vscode/extensions.json
.vscode/settings.json
Testing/VersionMinerIntegrationTests/IntegrationTests.cs
Testing/VersionMinerTests/Exceptions/RepoDoesNotExistExceptionTests.cs
Testing/VersionMinerTests/GitHubActionTests.cs
Testing/VersionMinerTests/Helpers/TestDataLoader.cs
VersionMiner.sln.DotSettings
VersionMiner/Exceptions/HeaderAlreadyExistsException.cs
VersionMiner/Exceptions/NoVersionFoundException.cs
VersionMiner/Exceptions/NoXMLElementException.cs
VersionMiner/Exceptions/NullOrEmptyStringException.cs
VersionMiner/Exceptions/RepoDoesNotExistException.cs
VersionMiner/Exceptions/ValuesMismatchException.cs
VersionMiner/Exceptions/VersionKeysNotFoundException.cs
VersionMiner/GitHubAction.cs
VersionMiner/Services/GitHubConsoleService.cs
VersionMiner/Services/IGitHubConsoleService.cs
VersionMiner/Services/XMLParserService.cs

<h1 style="font-weight:bold" align="center">Feature Pull Request</h1>
``` xml
Syntax: feature/<issue-num>-<description>
Example: feature/123-my-feature
```
</details>
💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/BranchingFeatureToMaster.md).
- One issue per pull request.
- This is required because unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests …

🐛Permission issue misleading

---

README.md

<h1 style="font-weight:bold" align="center">Feature Pull Request</h1>
``` xml
Syntax: feature/<issue-num>-<description>
Example: feature/123-my-feature
```
</details>
💡For more information on branching, refer to the project's [branching documentation](https://github.com/KinsonDigital/.github/blob/master/docs/BranchingFullGitFlow.md).
- One issue per pull request.
- The style is enforced by the **_.editorconfig_** files in the project and displayed as warnings.  If there is an edge case, reach out, and let's …

🚧Fix README badges

---

.github/workflows/add-new-issue-to-project.yml
.github/workflows/build-status-check.yml
.github/workflows/release.yml
.github/workflows/sync-bot.yml
.github/workflows/sync-issue-to-pr.yml
.github/workflows/sync-status-check.yml
.github/workflows/unit-testing-status-check.yml
README.md

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #150
✅ The pull request head branch must be a feature branch with the syntax `feature/<issue-num>-sync-testing`. 
✅ The pull request base branch must be 'main' or 'preview'. 
✅ The pull request head branch contains a valid issue number. 
✅ The pull request title matches the linked issue title exactly. 
✅ The pull request assignees match the assignees of the issue. 
✅ The pull request labels match the labels of the issue. 
✅ The pull request organizational projects match the organizational projects of the issue. 
✅ The pull requests milestone matches the milestone of the issue. 
---
1. Pull requests are automatically synced with the associated issue …

🚧Improve release workflow

---

.github/workflows/release.yml

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #155
✅The pull request head branch must be a feature branch with the syntax 'feature/<issue-num>-sync-testing'.  
✅The pull request base branch must be a 'main' or 'preview' branch..  
✅The pull request head branch contains a valid issue number.  
✅The pull request title matches the linked issue title exactly.  
✅The pull request assignees match the assignees of the issue.  
✅The pull request labels match the labels of the issue.  
✅The pull request organizational projects match the organizational projects of the issue.  
✅The pull requests milestone matches the milestone of the issue.  
---
1. Pull requests are automatically synced with the …

🚧Adjust release workflow input

---

.github/workflows/add-new-issue-to-project.yml
.github/workflows/build-status-check.yml
.github/workflows/prepare-release.yml
.github/workflows/release.yml
.github/workflows/sync-bot.yml
.github/workflows/unit-test-status-check.yml
README.md
Testing/VersionMinerTests/VersionMinerTests.csproj

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #157
✅The pull request head branch must be a feature branch with the syntax 'feature/<issue-num>-sync-testing'.  
✅The pull request base branch must be a 'main' or 'preview' branch..  
✅The pull request head branch contains a valid issue number.  
✅The pull request title matches the linked issue title exactly.  
✅The pull request assignees match the assignees of the issue.  
✅The pull request labels match the labels of the issue.  
✅The pull request organizational projects match the organizational projects of the issue.  
✅The pull requests milestone matches the milestone of the issue.  
---
1. Pull requests are automatically synced with the …

🚧Lock version of MOQ

---

Testing/VersionMinerTests/TestData/ProjFileTestSample.csproj

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.
This pull request closes #168
✅The pull request head branch must be a feature branch with the syntax 'feature/<issue-num>-sync-testing'.  
✅The pull request base branch must be a 'main' or 'preview' branch..  
✅The pull request head branch contains a valid issue number.  
✅The pull request title matches the linked issue title exactly.  
✅The pull request assignees match the assignees of the issue.  
✅The pull request labels match the labels of the issue.  
✅The pull request organizational projects match the organizational projects of the issue.  
✅The pull requests milestone matches the milestone of the issue.  
---
1. Pull requests are automatically synced with the …

🚧Remove the newtonsoft package
